### ISSUE TITLE
Bug Chrome 57

### ISSUE THREAD

**Issue by povbet** [folletto/Blipshot#15]
Hello,
Blipshot worked correctly with Chrome 56, but hangs with Chrome 57 (Slimjet 14), on the make icon, for any page lengths
Sincerely

**Comment by folletto** [comment]
Heya, I'm not able to test on Chrome 57 as mine has already updated, but I tried on Chrome 58 and it works. Can you try updating and see what happens? Thanks!

![screen shot 2017-05-28 at 13 41 40](https://cloud.githubusercontent.com/assets/4389/26528830/8c940d18-43ab-11e7-8330-481cf7b19669.png)

**Comment by a4jp-com** [comment]
I'm on Version 59.0.3071.115 (Official Build) (64-bit) and nothing is happening after the grab.

**Comment by folletto** [comment]
Can you please refer to which site are you trying on, and if you have errors in the console?

**Comment by a4jp-com** [comment]
[http://www.009.cd2.com/members/how_to/nouaillier_a.htm](url)

Error in event handler for runtime.onMessage: TypeError: Cannot read property '3' of null
    at dataToBlobURL (chrome-extension://mdaboflcmhejfihjcbmdiebgfchigjcf/screenshotter.DOM.js:187:28)
    at screenshotReturn (chrome-extension://mdaboflcmhejfihjcbmdiebgfchigjcf/screenshotter.DOM.js:80:19)
    at chrome-extension://mdaboflcmhejfihjcbmdiebgfchigjcf/screenshotter.DOM.js:121:36

**Comment by folletto** [comment]
Given the page length my first impression is that it might be a limit of size: Data URL which is used internally has a limit ([2Mb apparently](https://stackoverflow.com/questions/695151/data-protocol-url-size-limitations)).

I'll look into that, thanks!

**Comment by a4jp-com** [comment]
Great. Thanks for that.

**Comment by folletto** [comment]
I found the issue: apparently Chrome (Chromium) uses a library named Skia that has a limit on the maximum height and width of images. So the maximum image Chrome's `canvas` can generate is `32767px`.

I introduced a better handling in Blipshot 1.2.1 so at the very least it generates the image up to the limit. It's cut, but at least it's something.

Here the bug on Chromium [⌗339725](https://bugs.chromium.org/p/chromium/issues/detail?id=339725) (closed as `wontfix`)

Here the bug on Skia [⌗2122](https://bugs.chromium.org/p/skia/issues/detail?id=2122) (since 2014)

**Comment by a4jp-com** [comment]
Anything to either fix the bug or make everything work is cool.

**Comment by folletto** [comment]
I sample checked also other full-page screenshot extensions and they all have the same issue: they break at 32k pixels.

If you happen to find one that doesn't, let me know. :) 

Until then, we can just hope that someone in Google fixes it. Even if seems unlikely given it's open since 2014 and buried deep in the Skia library, while closed in Chromium. :(
